// AUTO-GENERATED by Prisma Style Dictionary build. Do not edit by hand.
// To regenerate: cd design-system && npm run build-tokens
// Source: design-system/tokens/*.json
// File: kotlin tokens for Jetpack Compose.

@file:Suppress("MagicNumber", "TopLevelPropertyNaming")

package xyz.ksharma.prisma.tokens

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Stable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object PrismaPrimitiveColors {
  // neutral
  val Neutral50: Color = Color(0xFFFAF8F5)
  val Neutral100: Color = Color(0xFFF2EFEA)
  val Neutral200: Color = Color(0xFFE6E1D9)
  val Neutral300: Color = Color(0xFFD2CBBF)
  val Neutral400: Color = Color(0xFFA8A092)
  val Neutral500: Color = Color(0xFF7C7567)
  val Neutral600: Color = Color(0xFF5A5447)
  val Neutral700: Color = Color(0xFF3F3A30)
  val Neutral800: Color = Color(0xFF2A2620)
  val Neutral900: Color = Color(0xFF1A1814)
  val Neutral950: Color = Color(0xFF0F0E0B)

  // accent
  val Accent50: Color = Color(0xFFFDF1E8)
  val Accent100: Color = Color(0xFFFADCC4)
  val Accent200: Color = Color(0xFFF5BC8E)
  val Accent300: Color = Color(0xFFEE9A5A)
  val Accent400: Color = Color(0xFFE07F3A)
  val Accent500: Color = Color(0xFFC66524)
  val Accent600: Color = Color(0xFFA24F18)
  val Accent700: Color = Color(0xFF7E3D11)
  val Accent800: Color = Color(0xFF5C2C0C)
  val Accent900: Color = Color(0xFF3D1D08)
  val Accent950: Color = Color(0xFF231005)

  // success
  val Success50: Color = Color(0xFFEEF4EC)
  val Success100: Color = Color(0xFFD4E4CE)
  val Success200: Color = Color(0xFFA9C99E)
  val Success300: Color = Color(0xFF7BAB6E)
  val Success400: Color = Color(0xFF558D49)
  val Success500: Color = Color(0xFF3F7235)
  val Success600: Color = Color(0xFF305827)
  val Success700: Color = Color(0xFF23401D)
  val Success800: Color = Color(0xFF192D15)
  val Success900: Color = Color(0xFF0F1B0D)
  val Success950: Color = Color(0xFF070D06)

  // warning
  val Warning50: Color = Color(0xFFFBF3E0)
  val Warning100: Color = Color(0xFFF5E2B6)
  val Warning200: Color = Color(0xFFEAC270)
  val Warning300: Color = Color(0xFFD69F36)
  val Warning400: Color = Color(0xFFB58420)
  val Warning500: Color = Color(0xFF8E6818)
  val Warning600: Color = Color(0xFF6E5012)
  val Warning700: Color = Color(0xFF523B0D)
  val Warning800: Color = Color(0xFF3A2A09)
  val Warning900: Color = Color(0xFF241A05)
  val Warning950: Color = Color(0xFF130E03)

  // danger
  val Danger50: Color = Color(0xFFFBECEA)
  val Danger100: Color = Color(0xFFF5CDC8)
  val Danger200: Color = Color(0xFFE89C92)
  val Danger300: Color = Color(0xFFD86E60)
  val Danger400: Color = Color(0xFFBF4A3B)
  val Danger500: Color = Color(0xFF9C3528)
  val Danger600: Color = Color(0xFF79281E)
  val Danger700: Color = Color(0xFF5A1D16)
  val Danger800: Color = Color(0xFF3F140F)
  val Danger900: Color = Color(0xFF260C09)
  val Danger950: Color = Color(0xFF150605)

  // info
  val Info50: Color = Color(0xFFEAF1F5)
  val Info100: Color = Color(0xFFC9DCE7)
  val Info200: Color = Color(0xFF92B6CB)
  val Info300: Color = Color(0xFF5C90AE)
  val Info400: Color = Color(0xFF3B7390)
  val Info500: Color = Color(0xFF2B5C75)
  val Info600: Color = Color(0xFF21475A)
  val Info700: Color = Color(0xFF193543)
  val Info800: Color = Color(0xFF11252F)
  val Info900: Color = Color(0xFF0A161C)
  val Info950: Color = Color(0xFF050B0E)

}

/** A colour that resolves differently in light vs. dark mode. */
@Stable
data class PrismaSemanticColor(val light: Color, val dark: Color) {
  @Composable fun resolve(): Color = if (isSystemInDarkTheme()) dark else light
  fun resolve(isDark: Boolean): Color = if (isDark) dark else light
}

object PrismaSemanticColors {
  val SurfaceBase: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFFAF8F5),
    dark  = Color(0xFF1A1814),
  )
  val SurfaceRaised: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFFFFFFF),
    dark  = Color(0xFF2A2620),
  )
  val SurfaceSunken: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFF2EFEA),
    dark  = Color(0xFF0F0E0B),
  )
  val SurfaceOverlay: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0x8C1A1814),
    dark  = Color(0xB80F0E0B),
  )
  val SurfaceInverse: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFF1A1814),
    dark  = Color(0xFFFAF8F5),
  )
  val TextPrimary: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFF1A1814),
    dark  = Color(0xFFFAF8F5),
  )
  val TextSecondary: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFF3F3A30),
    dark  = Color(0xFFE6E1D9),
  )
  val TextTertiary: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFF7C7567),
    dark  = Color(0xFFA8A092),
  )
  val TextDisabled: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFA8A092),
    dark  = Color(0xFF7C7567),
  )
  val TextOnAccent: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFFFFFFF),
    dark  = Color(0xFFFFFFFF),
  )
  val TextOnInverse: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFFAF8F5),
    dark  = Color(0xFF1A1814),
  )
  val TextLink: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFA24F18),
    dark  = Color(0xFFEE9A5A),
  )
  val BorderSubtle: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFE6E1D9),
    dark  = Color(0xFF2A2620),
  )
  val BorderDefault: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFD2CBBF),
    dark  = Color(0xFF3F3A30),
  )
  val BorderStrong: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFF7C7567),
    dark  = Color(0xFFA8A092),
  )
  val BorderFocus: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFC66524),
    dark  = Color(0xFFEE9A5A),
  )
  val AccentDefault: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFA24F18),
    dark  = Color(0xFFE07F3A),
  )
  val AccentHover: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFF7E3D11),
    dark  = Color(0xFFEE9A5A),
  )
  val AccentPressed: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFF5C2C0C),
    dark  = Color(0xFFF5BC8E),
  )
  val AccentSubtle: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFFDF1E8),
    dark  = Color(0xFF3D1D08),
  )
  val AccentOnAccent: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFFFFFFF),
    dark  = Color(0xFF0F0E0B),
  )
  val StatusSuccessDefault: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFF305827),
    dark  = Color(0xFF7BAB6E),
  )
  val StatusSuccessSubtle: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFEEF4EC),
    dark  = Color(0xFF0F1B0D),
  )
  val StatusSuccessOnStatus: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFFFFFFF),
    dark  = Color(0xFF0F0E0B),
  )
  val StatusWarningDefault: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFF6E5012),
    dark  = Color(0xFFD69F36),
  )
  val StatusWarningSubtle: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFFBF3E0),
    dark  = Color(0xFF241A05),
  )
  val StatusWarningOnStatus: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFFFFFFF),
    dark  = Color(0xFF0F0E0B),
  )
  val StatusDangerDefault: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFF79281E),
    dark  = Color(0xFFD86E60),
  )
  val StatusDangerSubtle: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFFBECEA),
    dark  = Color(0xFF260C09),
  )
  val StatusDangerOnStatus: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFFFFFFF),
    dark  = Color(0xFF0F0E0B),
  )
  val StatusInfoDefault: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFF21475A),
    dark  = Color(0xFF5C90AE),
  )
  val StatusInfoSubtle: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFEAF1F5),
    dark  = Color(0xFF0A161C),
  )
  val StatusInfoOnStatus: PrismaSemanticColor = PrismaSemanticColor(
    light = Color(0xFFFFFFFF),
    dark  = Color(0xFF0F0E0B),
  )
}

object PrismaSpacing {
  val Sp0: Dp = 0.dp
  val Sp1: Dp = 4.dp
  val Sp2: Dp = 8.dp
  val Sp3: Dp = 12.dp
  val Sp4: Dp = 16.dp
  val Sp5: Dp = 20.dp
  val Sp6: Dp = 24.dp
  val Sp7: Dp = 32.dp
  val Sp8: Dp = 40.dp
  val Sp9: Dp = 48.dp
  val Sp10: Dp = 64.dp
  val Sp11: Dp = 80.dp
  val Sp12: Dp = 96.dp
}

object PrismaRadius {
  val None: Dp = 0.dp
  val Sm: Dp = 4.dp
  val Md: Dp = 8.dp
  val Lg: Dp = 12.dp
  val Xl: Dp = 20.dp
  val Full: Dp = 9999.dp
}

/**
 * Typography tokens. References [PrismaFonts] which is hand-written in :core-ui
 * and registers FontFamily definitions for Instrument Sans and JetBrains Mono.
 */
object PrismaTypography {
  val DisplayLg: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(600),
    fontSize = 56.sp,
    lineHeight = 58.8.sp,
    letterSpacing = -1.12.sp,
  )
  val DisplayMd: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(600),
    fontSize = 44.sp,
    lineHeight = 47.52.sp,
    letterSpacing = -0.88.sp,
  )
  val DisplaySm: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(600),
    fontSize = 36.sp,
    lineHeight = 39.6.sp,
    letterSpacing = -0.648.sp,
  )
  val HeadlineLg: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(600),
    fontSize = 30.sp,
    lineHeight = 36.sp,
    letterSpacing = -0.42.sp,
  )
  val HeadlineMd: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(600),
    fontSize = 26.sp,
    lineHeight = 31.72.sp,
    letterSpacing = -0.312.sp,
  )
  val HeadlineSm: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(600),
    fontSize = 22.sp,
    lineHeight = 27.5.sp,
    letterSpacing = -0.22.sp,
  )
  val TitleLg: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(500),
    fontSize = 20.sp,
    lineHeight = 26.sp,
    letterSpacing = -0.12.sp,
  )
  val TitleMd: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(500),
    fontSize = 17.sp,
    lineHeight = 22.95.sp,
    letterSpacing = -0.068.sp,
  )
  val TitleSm: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(500),
    fontSize = 15.sp,
    lineHeight = 21.sp,
    letterSpacing = 0.sp,
  )
  val BodyLg: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(400),
    fontSize = 17.sp,
    lineHeight = 26.35.sp,
    letterSpacing = 0.sp,
  )
  val BodyMd: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(400),
    fontSize = 15.sp,
    lineHeight = 23.25.sp,
    letterSpacing = 0.sp,
  )
  val BodySm: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(400),
    fontSize = 13.sp,
    lineHeight = 19.5.sp,
    letterSpacing = 0.026.sp,
  )
  val LabelLg: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(500),
    fontSize = 15.sp,
    lineHeight = 19.5.sp,
    letterSpacing = 0.sp,
  )
  val LabelMd: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(500),
    fontSize = 13.sp,
    lineHeight = 16.9.sp,
    letterSpacing = 0.052.sp,
  )
  val LabelSm: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Sans,
    fontWeight = FontWeight(500),
    fontSize = 11.sp,
    lineHeight = 14.3.sp,
    letterSpacing = 0.44.sp,
  )
  val CodeMd: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Mono,
    fontWeight = FontWeight(400),
    fontSize = 14.sp,
    lineHeight = 21.sp,
    letterSpacing = 0.sp,
  )
  val CodeSm: TextStyle = TextStyle(
    fontFamily = PrismaFonts.Mono,
    fontWeight = FontWeight(400),
    fontSize = 12.sp,
    lineHeight = 18.sp,
    letterSpacing = 0.sp,
  )
}

/**
 * Multi-layer shadow specification. Render via Modifier.prismaShadow(level) defined in :core-ui.
 */
data class PrismaShadow(
  val offsetY: Dp,
  val blur: Dp,
  val spread: Dp,
  val color: Color,
  val inset: Boolean = false,
)

data class PrismaElevation(val light: List<PrismaShadow>, val dark: List<PrismaShadow>)

object PrismaElevations {
  val Level0: PrismaElevation = PrismaElevation(
    light = listOf(PrismaShadow(offsetY = 0.dp, blur = 0.dp, spread = 0.dp, color = Color(0x00000000))),
    dark  = listOf(PrismaShadow(offsetY = 0.dp, blur = 0.dp, spread = 0.dp, color = Color(0x00000000))),
  )
  val Level1: PrismaElevation = PrismaElevation(
    light = listOf(PrismaShadow(offsetY = 1.dp, blur = 2.dp, spread = 0.dp, color = Color(0x0A1A1814)), PrismaShadow(offsetY = 1.dp, blur = 3.dp, spread = 0.dp, color = Color(0x0F1A1814))),
    dark  = listOf(PrismaShadow(offsetY = 0.dp, blur = 0.dp, spread = 1.dp, color = Color(0x0AFFFFFF), inset = true), PrismaShadow(offsetY = 1.dp, blur = 2.dp, spread = 0.dp, color = Color(0x66000000))),
  )
  val Level2: PrismaElevation = PrismaElevation(
    light = listOf(PrismaShadow(offsetY = 2.dp, blur = 4.dp, spread = 0.dp, color = Color(0x0D1A1814)), PrismaShadow(offsetY = 4.dp, blur = 8.dp, spread = 0.dp, color = Color(0x141A1814))),
    dark  = listOf(PrismaShadow(offsetY = 0.dp, blur = 0.dp, spread = 1.dp, color = Color(0x0DFFFFFF), inset = true), PrismaShadow(offsetY = 2.dp, blur = 8.dp, spread = 0.dp, color = Color(0x80000000))),
  )
  val Level3: PrismaElevation = PrismaElevation(
    light = listOf(PrismaShadow(offsetY = 4.dp, blur = 8.dp, spread = 0.dp, color = Color(0x0F1A1814)), PrismaShadow(offsetY = 8.dp, blur = 16.dp, spread = -2.dp, color = Color(0x1A1A1814))),
    dark  = listOf(PrismaShadow(offsetY = 0.dp, blur = 0.dp, spread = 1.dp, color = Color(0x0FFFFFFF), inset = true), PrismaShadow(offsetY = 4.dp, blur = 16.dp, spread = 0.dp, color = Color(0x99000000))),
  )
  val Level4: PrismaElevation = PrismaElevation(
    light = listOf(PrismaShadow(offsetY = 8.dp, blur = 16.dp, spread = 0.dp, color = Color(0x141A1814)), PrismaShadow(offsetY = 16.dp, blur = 32.dp, spread = -4.dp, color = Color(0x1F1A1814))),
    dark  = listOf(PrismaShadow(offsetY = 0.dp, blur = 0.dp, spread = 1.dp, color = Color(0x14FFFFFF), inset = true), PrismaShadow(offsetY = 8.dp, blur = 32.dp, spread = 0.dp, color = Color(0xB3000000))),
  )
  val Level5: PrismaElevation = PrismaElevation(
    light = listOf(PrismaShadow(offsetY = 16.dp, blur = 32.dp, spread = 0.dp, color = Color(0x1A1A1814)), PrismaShadow(offsetY = 24.dp, blur = 48.dp, spread = -8.dp, color = Color(0x241A1814))),
    dark  = listOf(PrismaShadow(offsetY = 0.dp, blur = 0.dp, spread = 1.dp, color = Color(0x1AFFFFFF), inset = true), PrismaShadow(offsetY = 0.dp, blur = 24.dp, spread = 0.dp, color = Color(0x14C66524)), PrismaShadow(offsetY = 16.dp, blur = 48.dp, spread = 0.dp, color = Color(0xCC000000))),
  )
}

object PrismaMotion {
  object Duration {
    const val Instant: Int = 0 // ms
    const val Fast: Int = 120 // ms
    const val Default: Int = 220 // ms
    const val Slow: Int = 360 // ms
    const val Slower: Int = 520 // ms
  }

  /** Cubic Bézier control points (x1, y1, x2, y2). Use Compose CubicBezierEasing. */
  object Easing {
    val Linear: FloatArray = floatArrayOf(0f, 0f, 1f, 1f)
    val Standard: FloatArray = floatArrayOf(0.2f, 0f, 0f, 1f)
    val Decelerate: FloatArray = floatArrayOf(0f, 0f, 0.2f, 1f)
    val Accelerate: FloatArray = floatArrayOf(0.4f, 0f, 1f, 1f)
    val Emphasized: FloatArray = floatArrayOf(0.3f, 0f, 0f, 1f)
    val Spring: FloatArray = floatArrayOf(0.34f, 1.56f, 0.64f, 1f)
  }
}
