// AUTO-GENERATED by Prisma Style Dictionary build. Do not edit by hand.
// To regenerate: cd design-system && npm run build-tokens
// Source: design-system/tokens/*.json
// File: swift tokens for SwiftUI.


import SwiftUI

public enum PrismaPrimitiveColors {
  // MARK: - neutral
  public static let neutral50: Color = Color(.sRGB, red: 0.9804, green: 0.9725, blue: 0.9608, opacity: 1)
  public static let neutral100: Color = Color(.sRGB, red: 0.949, green: 0.9373, blue: 0.9176, opacity: 1)
  public static let neutral200: Color = Color(.sRGB, red: 0.902, green: 0.8824, blue: 0.851, opacity: 1)
  public static let neutral300: Color = Color(.sRGB, red: 0.8235, green: 0.7961, blue: 0.749, opacity: 1)
  public static let neutral400: Color = Color(.sRGB, red: 0.6588, green: 0.6275, blue: 0.5725, opacity: 1)
  public static let neutral500: Color = Color(.sRGB, red: 0.4863, green: 0.4588, blue: 0.4039, opacity: 1)
  public static let neutral600: Color = Color(.sRGB, red: 0.3529, green: 0.3294, blue: 0.2784, opacity: 1)
  public static let neutral700: Color = Color(.sRGB, red: 0.2471, green: 0.2275, blue: 0.1882, opacity: 1)
  public static let neutral800: Color = Color(.sRGB, red: 0.1647, green: 0.149, blue: 0.1255, opacity: 1)
  public static let neutral900: Color = Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 1)
  public static let neutral950: Color = Color(.sRGB, red: 0.0588, green: 0.0549, blue: 0.0431, opacity: 1)

  // MARK: - accent
  public static let accent50: Color = Color(.sRGB, red: 0.9922, green: 0.9451, blue: 0.9098, opacity: 1)
  public static let accent100: Color = Color(.sRGB, red: 0.9804, green: 0.8627, blue: 0.7686, opacity: 1)
  public static let accent200: Color = Color(.sRGB, red: 0.9608, green: 0.7373, blue: 0.5569, opacity: 1)
  public static let accent300: Color = Color(.sRGB, red: 0.9333, green: 0.6039, blue: 0.3529, opacity: 1)
  public static let accent400: Color = Color(.sRGB, red: 0.8784, green: 0.498, blue: 0.2275, opacity: 1)
  public static let accent500: Color = Color(.sRGB, red: 0.7765, green: 0.3961, blue: 0.1412, opacity: 1)
  public static let accent600: Color = Color(.sRGB, red: 0.6353, green: 0.3098, blue: 0.0941, opacity: 1)
  public static let accent700: Color = Color(.sRGB, red: 0.4941, green: 0.2392, blue: 0.0667, opacity: 1)
  public static let accent800: Color = Color(.sRGB, red: 0.3608, green: 0.1725, blue: 0.0471, opacity: 1)
  public static let accent900: Color = Color(.sRGB, red: 0.2392, green: 0.1137, blue: 0.0314, opacity: 1)
  public static let accent950: Color = Color(.sRGB, red: 0.1373, green: 0.0627, blue: 0.0196, opacity: 1)

  // MARK: - success
  public static let success50: Color = Color(.sRGB, red: 0.9333, green: 0.9569, blue: 0.9255, opacity: 1)
  public static let success100: Color = Color(.sRGB, red: 0.8314, green: 0.8941, blue: 0.8078, opacity: 1)
  public static let success200: Color = Color(.sRGB, red: 0.6627, green: 0.7882, blue: 0.6196, opacity: 1)
  public static let success300: Color = Color(.sRGB, red: 0.4824, green: 0.6706, blue: 0.4314, opacity: 1)
  public static let success400: Color = Color(.sRGB, red: 0.3333, green: 0.5529, blue: 0.2863, opacity: 1)
  public static let success500: Color = Color(.sRGB, red: 0.2471, green: 0.4471, blue: 0.2078, opacity: 1)
  public static let success600: Color = Color(.sRGB, red: 0.1882, green: 0.3451, blue: 0.1529, opacity: 1)
  public static let success700: Color = Color(.sRGB, red: 0.1373, green: 0.251, blue: 0.1137, opacity: 1)
  public static let success800: Color = Color(.sRGB, red: 0.098, green: 0.1765, blue: 0.0824, opacity: 1)
  public static let success900: Color = Color(.sRGB, red: 0.0588, green: 0.1059, blue: 0.051, opacity: 1)
  public static let success950: Color = Color(.sRGB, red: 0.0275, green: 0.051, blue: 0.0235, opacity: 1)

  // MARK: - warning
  public static let warning50: Color = Color(.sRGB, red: 0.9843, green: 0.9529, blue: 0.8784, opacity: 1)
  public static let warning100: Color = Color(.sRGB, red: 0.9608, green: 0.8863, blue: 0.7137, opacity: 1)
  public static let warning200: Color = Color(.sRGB, red: 0.9176, green: 0.7608, blue: 0.4392, opacity: 1)
  public static let warning300: Color = Color(.sRGB, red: 0.8392, green: 0.6235, blue: 0.2118, opacity: 1)
  public static let warning400: Color = Color(.sRGB, red: 0.7098, green: 0.5176, blue: 0.1255, opacity: 1)
  public static let warning500: Color = Color(.sRGB, red: 0.5569, green: 0.4078, blue: 0.0941, opacity: 1)
  public static let warning600: Color = Color(.sRGB, red: 0.4314, green: 0.3137, blue: 0.0706, opacity: 1)
  public static let warning700: Color = Color(.sRGB, red: 0.3216, green: 0.2314, blue: 0.051, opacity: 1)
  public static let warning800: Color = Color(.sRGB, red: 0.2275, green: 0.1647, blue: 0.0353, opacity: 1)
  public static let warning900: Color = Color(.sRGB, red: 0.1412, green: 0.102, blue: 0.0196, opacity: 1)
  public static let warning950: Color = Color(.sRGB, red: 0.0745, green: 0.0549, blue: 0.0118, opacity: 1)

  // MARK: - danger
  public static let danger50: Color = Color(.sRGB, red: 0.9843, green: 0.9255, blue: 0.9176, opacity: 1)
  public static let danger100: Color = Color(.sRGB, red: 0.9608, green: 0.8039, blue: 0.7843, opacity: 1)
  public static let danger200: Color = Color(.sRGB, red: 0.9098, green: 0.6118, blue: 0.5725, opacity: 1)
  public static let danger300: Color = Color(.sRGB, red: 0.8471, green: 0.4314, blue: 0.3765, opacity: 1)
  public static let danger400: Color = Color(.sRGB, red: 0.749, green: 0.2902, blue: 0.2314, opacity: 1)
  public static let danger500: Color = Color(.sRGB, red: 0.6118, green: 0.2078, blue: 0.1569, opacity: 1)
  public static let danger600: Color = Color(.sRGB, red: 0.4745, green: 0.1569, blue: 0.1176, opacity: 1)
  public static let danger700: Color = Color(.sRGB, red: 0.3529, green: 0.1137, blue: 0.0863, opacity: 1)
  public static let danger800: Color = Color(.sRGB, red: 0.2471, green: 0.0784, blue: 0.0588, opacity: 1)
  public static let danger900: Color = Color(.sRGB, red: 0.149, green: 0.0471, blue: 0.0353, opacity: 1)
  public static let danger950: Color = Color(.sRGB, red: 0.0824, green: 0.0235, blue: 0.0196, opacity: 1)

  // MARK: - info
  public static let info50: Color = Color(.sRGB, red: 0.9176, green: 0.9451, blue: 0.9608, opacity: 1)
  public static let info100: Color = Color(.sRGB, red: 0.7882, green: 0.8627, blue: 0.9059, opacity: 1)
  public static let info200: Color = Color(.sRGB, red: 0.5725, green: 0.7137, blue: 0.7961, opacity: 1)
  public static let info300: Color = Color(.sRGB, red: 0.3608, green: 0.5647, blue: 0.6824, opacity: 1)
  public static let info400: Color = Color(.sRGB, red: 0.2314, green: 0.451, blue: 0.5647, opacity: 1)
  public static let info500: Color = Color(.sRGB, red: 0.1686, green: 0.3608, blue: 0.4588, opacity: 1)
  public static let info600: Color = Color(.sRGB, red: 0.1294, green: 0.2784, blue: 0.3529, opacity: 1)
  public static let info700: Color = Color(.sRGB, red: 0.098, green: 0.2078, blue: 0.2627, opacity: 1)
  public static let info800: Color = Color(.sRGB, red: 0.0667, green: 0.1451, blue: 0.1843, opacity: 1)
  public static let info900: Color = Color(.sRGB, red: 0.0392, green: 0.0863, blue: 0.1098, opacity: 1)
  public static let info950: Color = Color(.sRGB, red: 0.0196, green: 0.0431, blue: 0.0549, opacity: 1)

}

/// A colour that resolves differently in light vs. dark mode.
public struct PrismaSemanticColor: Equatable {
  public let light: Color
  public let dark: Color
  public init(light: Color, dark: Color) { self.light = light; self.dark = dark }
  public func resolve(_ scheme: ColorScheme) -> Color { scheme == .dark ? dark : light }
}

public enum PrismaSemanticColors {
  public static let surfaceBase: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.9804, green: 0.9725, blue: 0.9608, opacity: 1),
    dark:  Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 1)
  )
  public static let surfaceRaised: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1),
    dark:  Color(.sRGB, red: 0.1647, green: 0.149, blue: 0.1255, opacity: 1)
  )
  public static let surfaceSunken: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.949, green: 0.9373, blue: 0.9176, opacity: 1),
    dark:  Color(.sRGB, red: 0.0588, green: 0.0549, blue: 0.0431, opacity: 1)
  )
  public static let surfaceOverlay: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 0.55),
    dark:  Color(.sRGB, red: 0.0588, green: 0.0549, blue: 0.0431, opacity: 0.72)
  )
  public static let surfaceInverse: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 1),
    dark:  Color(.sRGB, red: 0.9804, green: 0.9725, blue: 0.9608, opacity: 1)
  )
  public static let textPrimary: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 1),
    dark:  Color(.sRGB, red: 0.9804, green: 0.9725, blue: 0.9608, opacity: 1)
  )
  public static let textSecondary: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.2471, green: 0.2275, blue: 0.1882, opacity: 1),
    dark:  Color(.sRGB, red: 0.902, green: 0.8824, blue: 0.851, opacity: 1)
  )
  public static let textTertiary: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.4863, green: 0.4588, blue: 0.4039, opacity: 1),
    dark:  Color(.sRGB, red: 0.6588, green: 0.6275, blue: 0.5725, opacity: 1)
  )
  public static let textDisabled: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.6588, green: 0.6275, blue: 0.5725, opacity: 1),
    dark:  Color(.sRGB, red: 0.4863, green: 0.4588, blue: 0.4039, opacity: 1)
  )
  public static let textOnAccent: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1),
    dark:  Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1)
  )
  public static let textOnInverse: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.9804, green: 0.9725, blue: 0.9608, opacity: 1),
    dark:  Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 1)
  )
  public static let textLink: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.6353, green: 0.3098, blue: 0.0941, opacity: 1),
    dark:  Color(.sRGB, red: 0.9333, green: 0.6039, blue: 0.3529, opacity: 1)
  )
  public static let borderSubtle: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.902, green: 0.8824, blue: 0.851, opacity: 1),
    dark:  Color(.sRGB, red: 0.1647, green: 0.149, blue: 0.1255, opacity: 1)
  )
  public static let borderDefault: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.8235, green: 0.7961, blue: 0.749, opacity: 1),
    dark:  Color(.sRGB, red: 0.2471, green: 0.2275, blue: 0.1882, opacity: 1)
  )
  public static let borderStrong: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.4863, green: 0.4588, blue: 0.4039, opacity: 1),
    dark:  Color(.sRGB, red: 0.6588, green: 0.6275, blue: 0.5725, opacity: 1)
  )
  public static let borderFocus: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.7765, green: 0.3961, blue: 0.1412, opacity: 1),
    dark:  Color(.sRGB, red: 0.9333, green: 0.6039, blue: 0.3529, opacity: 1)
  )
  public static let accentDefault: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.6353, green: 0.3098, blue: 0.0941, opacity: 1),
    dark:  Color(.sRGB, red: 0.8784, green: 0.498, blue: 0.2275, opacity: 1)
  )
  public static let accentHover: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.4941, green: 0.2392, blue: 0.0667, opacity: 1),
    dark:  Color(.sRGB, red: 0.9333, green: 0.6039, blue: 0.3529, opacity: 1)
  )
  public static let accentPressed: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.3608, green: 0.1725, blue: 0.0471, opacity: 1),
    dark:  Color(.sRGB, red: 0.9608, green: 0.7373, blue: 0.5569, opacity: 1)
  )
  public static let accentSubtle: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.9922, green: 0.9451, blue: 0.9098, opacity: 1),
    dark:  Color(.sRGB, red: 0.2392, green: 0.1137, blue: 0.0314, opacity: 1)
  )
  public static let accentOnAccent: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1),
    dark:  Color(.sRGB, red: 0.0588, green: 0.0549, blue: 0.0431, opacity: 1)
  )
  public static let statusSuccessDefault: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.1882, green: 0.3451, blue: 0.1529, opacity: 1),
    dark:  Color(.sRGB, red: 0.4824, green: 0.6706, blue: 0.4314, opacity: 1)
  )
  public static let statusSuccessSubtle: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.9333, green: 0.9569, blue: 0.9255, opacity: 1),
    dark:  Color(.sRGB, red: 0.0588, green: 0.1059, blue: 0.051, opacity: 1)
  )
  public static let statusSuccessOnStatus: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1),
    dark:  Color(.sRGB, red: 0.0588, green: 0.0549, blue: 0.0431, opacity: 1)
  )
  public static let statusWarningDefault: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.4314, green: 0.3137, blue: 0.0706, opacity: 1),
    dark:  Color(.sRGB, red: 0.8392, green: 0.6235, blue: 0.2118, opacity: 1)
  )
  public static let statusWarningSubtle: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.9843, green: 0.9529, blue: 0.8784, opacity: 1),
    dark:  Color(.sRGB, red: 0.1412, green: 0.102, blue: 0.0196, opacity: 1)
  )
  public static let statusWarningOnStatus: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1),
    dark:  Color(.sRGB, red: 0.0588, green: 0.0549, blue: 0.0431, opacity: 1)
  )
  public static let statusDangerDefault: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.4745, green: 0.1569, blue: 0.1176, opacity: 1),
    dark:  Color(.sRGB, red: 0.8471, green: 0.4314, blue: 0.3765, opacity: 1)
  )
  public static let statusDangerSubtle: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.9843, green: 0.9255, blue: 0.9176, opacity: 1),
    dark:  Color(.sRGB, red: 0.149, green: 0.0471, blue: 0.0353, opacity: 1)
  )
  public static let statusDangerOnStatus: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1),
    dark:  Color(.sRGB, red: 0.0588, green: 0.0549, blue: 0.0431, opacity: 1)
  )
  public static let statusInfoDefault: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.1294, green: 0.2784, blue: 0.3529, opacity: 1),
    dark:  Color(.sRGB, red: 0.3608, green: 0.5647, blue: 0.6824, opacity: 1)
  )
  public static let statusInfoSubtle: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 0.9176, green: 0.9451, blue: 0.9608, opacity: 1),
    dark:  Color(.sRGB, red: 0.0392, green: 0.0863, blue: 0.1098, opacity: 1)
  )
  public static let statusInfoOnStatus: PrismaSemanticColor = PrismaSemanticColor(
    light: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1),
    dark:  Color(.sRGB, red: 0.0588, green: 0.0549, blue: 0.0431, opacity: 1)
  )
}

public enum PrismaSpacing {
  public static let sp0: CGFloat = 0
  public static let sp1: CGFloat = 4
  public static let sp2: CGFloat = 8
  public static let sp3: CGFloat = 12
  public static let sp4: CGFloat = 16
  public static let sp5: CGFloat = 20
  public static let sp6: CGFloat = 24
  public static let sp7: CGFloat = 32
  public static let sp8: CGFloat = 40
  public static let sp9: CGFloat = 48
  public static let sp10: CGFloat = 64
  public static let sp11: CGFloat = 80
  public static let sp12: CGFloat = 96
}

public enum PrismaRadius {
  public static let none: CGFloat = 0
  public static let sm: CGFloat = 4
  public static let md: CGFloat = 8
  public static let lg: CGFloat = 12
  public static let xl: CGFloat = 20
  public static let full: CGFloat = 9999
}

/// Typography tokens. References [PrismaFonts] which is hand-written in CoreUI
/// and registers Instrument Sans + JetBrains Mono via Resources/Fonts/.
public enum PrismaTypography {
  public struct Style: Equatable {
    public let font: Font
    public let lineHeight: CGFloat
    public let letterSpacing: CGFloat
    public init(font: Font, lineHeight: CGFloat, letterSpacing: CGFloat) {
      self.font = font; self.lineHeight = lineHeight; self.letterSpacing = letterSpacing
    }
  }

  public static let displayLg: Style = Style(
    font: PrismaFonts.sans(size: 56, weight: .semibold),
    lineHeight: 58.8,
    letterSpacing: -1.12
  )
  public static let displayMd: Style = Style(
    font: PrismaFonts.sans(size: 44, weight: .semibold),
    lineHeight: 47.52,
    letterSpacing: -0.88
  )
  public static let displaySm: Style = Style(
    font: PrismaFonts.sans(size: 36, weight: .semibold),
    lineHeight: 39.6,
    letterSpacing: -0.648
  )
  public static let headlineLg: Style = Style(
    font: PrismaFonts.sans(size: 30, weight: .semibold),
    lineHeight: 36,
    letterSpacing: -0.42
  )
  public static let headlineMd: Style = Style(
    font: PrismaFonts.sans(size: 26, weight: .semibold),
    lineHeight: 31.72,
    letterSpacing: -0.312
  )
  public static let headlineSm: Style = Style(
    font: PrismaFonts.sans(size: 22, weight: .semibold),
    lineHeight: 27.5,
    letterSpacing: -0.22
  )
  public static let titleLg: Style = Style(
    font: PrismaFonts.sans(size: 20, weight: .medium),
    lineHeight: 26,
    letterSpacing: -0.12
  )
  public static let titleMd: Style = Style(
    font: PrismaFonts.sans(size: 17, weight: .medium),
    lineHeight: 22.95,
    letterSpacing: -0.068
  )
  public static let titleSm: Style = Style(
    font: PrismaFonts.sans(size: 15, weight: .medium),
    lineHeight: 21,
    letterSpacing: 0
  )
  public static let bodyLg: Style = Style(
    font: PrismaFonts.sans(size: 17, weight: .regular),
    lineHeight: 26.35,
    letterSpacing: 0
  )
  public static let bodyMd: Style = Style(
    font: PrismaFonts.sans(size: 15, weight: .regular),
    lineHeight: 23.25,
    letterSpacing: 0
  )
  public static let bodySm: Style = Style(
    font: PrismaFonts.sans(size: 13, weight: .regular),
    lineHeight: 19.5,
    letterSpacing: 0.026
  )
  public static let labelLg: Style = Style(
    font: PrismaFonts.sans(size: 15, weight: .medium),
    lineHeight: 19.5,
    letterSpacing: 0
  )
  public static let labelMd: Style = Style(
    font: PrismaFonts.sans(size: 13, weight: .medium),
    lineHeight: 16.9,
    letterSpacing: 0.052
  )
  public static let labelSm: Style = Style(
    font: PrismaFonts.sans(size: 11, weight: .medium),
    lineHeight: 14.3,
    letterSpacing: 0.44
  )
  public static let codeMd: Style = Style(
    font: PrismaFonts.mono(size: 14, weight: .regular),
    lineHeight: 21,
    letterSpacing: 0
  )
  public static let codeSm: Style = Style(
    font: PrismaFonts.mono(size: 12, weight: .regular),
    lineHeight: 18,
    letterSpacing: 0
  )
}

public struct PrismaShadow: Equatable {
  public let offsetY: CGFloat
  public let blur: CGFloat
  public let spread: CGFloat
  public let color: Color
  public let inset: Bool
  public init(offsetY: CGFloat, blur: CGFloat, spread: CGFloat, color: Color, inset: Bool = false) {
    self.offsetY = offsetY; self.blur = blur; self.spread = spread; self.color = color; self.inset = inset
  }
}

public struct PrismaElevation: Equatable {
  public let light: [PrismaShadow]
  public let dark: [PrismaShadow]
  public init(light: [PrismaShadow], dark: [PrismaShadow]) { self.light = light; self.dark = dark }
}

public enum PrismaElevations {
  public static let level0: PrismaElevation = PrismaElevation(
    light: [PrismaShadow(offsetY: 0, blur: 0, spread: 0, color: Color(.sRGB, red: 0, green: 0, blue: 0, opacity: 0))],
    dark:  [PrismaShadow(offsetY: 0, blur: 0, spread: 0, color: Color(.sRGB, red: 0, green: 0, blue: 0, opacity: 0))]
  )
  public static let level1: PrismaElevation = PrismaElevation(
    light: [PrismaShadow(offsetY: 1, blur: 2, spread: 0, color: Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 0.04)), PrismaShadow(offsetY: 1, blur: 3, spread: 0, color: Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 0.06))],
    dark:  [PrismaShadow(offsetY: 0, blur: 0, spread: 1, color: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 0.04), inset: true), PrismaShadow(offsetY: 1, blur: 2, spread: 0, color: Color(.sRGB, red: 0, green: 0, blue: 0, opacity: 0.4))]
  )
  public static let level2: PrismaElevation = PrismaElevation(
    light: [PrismaShadow(offsetY: 2, blur: 4, spread: 0, color: Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 0.05)), PrismaShadow(offsetY: 4, blur: 8, spread: 0, color: Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 0.08))],
    dark:  [PrismaShadow(offsetY: 0, blur: 0, spread: 1, color: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 0.05), inset: true), PrismaShadow(offsetY: 2, blur: 8, spread: 0, color: Color(.sRGB, red: 0, green: 0, blue: 0, opacity: 0.5))]
  )
  public static let level3: PrismaElevation = PrismaElevation(
    light: [PrismaShadow(offsetY: 4, blur: 8, spread: 0, color: Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 0.06)), PrismaShadow(offsetY: 8, blur: 16, spread: -2, color: Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 0.1))],
    dark:  [PrismaShadow(offsetY: 0, blur: 0, spread: 1, color: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 0.06), inset: true), PrismaShadow(offsetY: 4, blur: 16, spread: 0, color: Color(.sRGB, red: 0, green: 0, blue: 0, opacity: 0.6))]
  )
  public static let level4: PrismaElevation = PrismaElevation(
    light: [PrismaShadow(offsetY: 8, blur: 16, spread: 0, color: Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 0.08)), PrismaShadow(offsetY: 16, blur: 32, spread: -4, color: Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 0.12))],
    dark:  [PrismaShadow(offsetY: 0, blur: 0, spread: 1, color: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 0.08), inset: true), PrismaShadow(offsetY: 8, blur: 32, spread: 0, color: Color(.sRGB, red: 0, green: 0, blue: 0, opacity: 0.7))]
  )
  public static let level5: PrismaElevation = PrismaElevation(
    light: [PrismaShadow(offsetY: 16, blur: 32, spread: 0, color: Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 0.1)), PrismaShadow(offsetY: 24, blur: 48, spread: -8, color: Color(.sRGB, red: 0.102, green: 0.0941, blue: 0.0784, opacity: 0.14))],
    dark:  [PrismaShadow(offsetY: 0, blur: 0, spread: 1, color: Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 0.1), inset: true), PrismaShadow(offsetY: 0, blur: 24, spread: 0, color: Color(.sRGB, red: 0.7765, green: 0.3961, blue: 0.1412, opacity: 0.08)), PrismaShadow(offsetY: 16, blur: 48, spread: 0, color: Color(.sRGB, red: 0, green: 0, blue: 0, opacity: 0.8))]
  )
}

public enum PrismaMotion {
  /// Durations in seconds (suitable for SwiftUI Animation).
  public enum Duration {
    public static let instant: Double = 0 // 0ms
    public static let fast: Double = 0.12 // 120ms
    public static let `default`: Double = 0.22 // 220ms
    public static let slow: Double = 0.36 // 360ms
    public static let slower: Double = 0.52 // 520ms
  }

  /// Cubic Bézier control points (x1, y1, x2, y2). Build SwiftUI Animation.timingCurve.
  public enum Easing {
    public static let linear: (Double, Double, Double, Double) = (0, 0, 1, 1)
    public static let standard: (Double, Double, Double, Double) = (0.2, 0, 0, 1)
    public static let decelerate: (Double, Double, Double, Double) = (0, 0, 0.2, 1)
    public static let accelerate: (Double, Double, Double, Double) = (0.4, 0, 1, 1)
    public static let emphasized: (Double, Double, Double, Double) = (0.3, 0, 0, 1)
    public static let spring: (Double, Double, Double, Double) = (0.34, 1.56, 0.64, 1)
  }
}
