// Shared helpers for token transforms.

// "16px" → 16. Returns NaN if not parseable.
export const parsePx = (v) => {
  if (typeof v === 'number') return v;
  if (typeof v !== 'string') return NaN;
  const m = v.match(/^(-?[\d.]+)\s*(px|pt|dp|sp|rem|em)?$/);
  return m ? parseFloat(m[1]) : NaN;
};

// "120ms" → 120 (millis as int)
export const parseMs = (v) => {
  if (typeof v === 'number') return Math.round(v);
  const m = String(v).match(/^(-?[\d.]+)\s*ms$/);
  return m ? Math.round(parseFloat(m[1])) : NaN;
};

// "-0.02em" relative to 56px → letter-spacing in px
export const resolveEm = (value, basePx) => {
  if (typeof value === 'number') return value;
  const s = String(value).trim();
  if (s === '0' || s === '0px' || s === '0em') return 0;
  const m = s.match(/^(-?[\d.]+)\s*em$/);
  if (m) return parseFloat(m[1]) * basePx;
  return parsePx(s);
};

// "1.05" or "58.8px" → resolved line height in px relative to fontSize
export const resolveLineHeight = (value, basePx) => {
  if (typeof value === 'number') {
    return value < 4 ? value * basePx : value; // unit-less multiplier vs absolute
  }
  const s = String(value).trim();
  if (/^[\d.]+$/.test(s)) {
    const n = parseFloat(s);
    return n < 4 ? n * basePx : n;
  }
  return parsePx(s);
};

// "#FAF8F5" → 0xFFFAF8F5  (Compose ARGB long literal)
// "#FAF8F5CC" / "rgba(...)" → preserves alpha
export const hexToARGB = (input) => {
  const s = String(input).trim().toLowerCase();

  if (s === 'transparent') return '0x00000000';

  if (s.startsWith('#')) {
    let hex = s.slice(1);
    if (hex.length === 3) hex = hex.split('').map((c) => c + c).join('');
    if (hex.length === 6) return `0xFF${hex.toUpperCase()}`;
    if (hex.length === 8) {
      // CSS is RRGGBBAA; Compose needs AARRGGBB
      const r = hex.slice(0, 2), g = hex.slice(2, 4), b = hex.slice(4, 6), a = hex.slice(6, 8);
      return `0x${a}${r}${g}${b}`.toUpperCase().replace('0X', '0x');
    }
  }

  const rgba = s.match(/^rgba?\(([^)]+)\)$/);
  if (rgba) {
    const parts = rgba[1].split(',').map((p) => p.trim());
    const r = parseInt(parts[0], 10);
    const g = parseInt(parts[1], 10);
    const b = parseInt(parts[2], 10);
    const a = parts[3] !== undefined ? Math.round(parseFloat(parts[3]) * 255) : 255;
    const hex = (n) => n.toString(16).padStart(2, '0').toUpperCase();
    return `0x${hex(a)}${hex(r)}${hex(g)}${hex(b)}`;
  }

  console.warn(`[utils] Unrecognised colour value: ${input}`);
  return '0xFF000000';
};

// "#FAF8F5" → { r:0.98, g:0.972, b:0.961, a:1 } (SwiftUI Color components)
export const hexToRGBA = (input) => {
  const s = String(input).trim().toLowerCase();
  if (s === 'transparent') return { r: 0, g: 0, b: 0, a: 0 };

  if (s.startsWith('#')) {
    let hex = s.slice(1);
    if (hex.length === 3) hex = hex.split('').map((c) => c + c).join('');
    const r = parseInt(hex.slice(0, 2), 16) / 255;
    const g = parseInt(hex.slice(2, 4), 16) / 255;
    const b = parseInt(hex.slice(4, 6), 16) / 255;
    const a = hex.length === 8 ? parseInt(hex.slice(6, 8), 16) / 255 : 1;
    return { r, g, b, a };
  }

  const rgba = s.match(/^rgba?\(([^)]+)\)$/);
  if (rgba) {
    const parts = rgba[1].split(',').map((p) => p.trim());
    return {
      r: parseInt(parts[0], 10) / 255,
      g: parseInt(parts[1], 10) / 255,
      b: parseInt(parts[2], 10) / 255,
      a: parts[3] !== undefined ? parseFloat(parts[3]) : 1,
    };
  }

  console.warn(`[utils] Unrecognised colour value: ${input}`);
  return { r: 0, g: 0, b: 0, a: 1 };
};

// 4-decimal float for Swift literals.
export const f = (n) => Number(n.toFixed(4)).toString();

// "neutral.50" → "Neutral50";  "display.lg" → "DisplayLg";  "primary" → "Primary"
export const pascalCase = (parts) =>
  parts
    .map((p) => p.replace(/[^a-zA-Z0-9]+/g, ' ').trim())
    .map((p) => p.split(/\s+/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(''))
    .join('');

// "neutral.50" → "neutral50";  "display.lg" → "displayLg"
export const camelCase = (parts) => {
  const pascal = pascalCase(parts);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
};

// Detects font family — match the reference label from typography.json
export const fontFamilyKey = (resolvedFamily) => {
  const s = String(resolvedFamily || '').toLowerCase();
  if (s.startsWith('jetbrains')) return 'Mono';
  if (s.startsWith('instrument')) return 'Sans';
  return 'Sans'; // default fallback
};

// CSS "cubic-bezier(a, b, c, d)" → [a, b, c, d]
export const parseCubicBezier = (v) => {
  const m = String(v).match(/cubic-bezier\(([^)]+)\)/);
  if (!m) return [0.4, 0, 0.2, 1]; // sensible default
  return m[1].split(',').map((p) => parseFloat(p.trim()));
};

export const banner = (kind) =>
  `// AUTO-GENERATED by Prisma Style Dictionary build. Do not edit by hand.\n` +
  `// To regenerate: cd design-system && npm run build-tokens\n` +
  `// Source: design-system/tokens/*.json\n` +
  (kind === 'kotlin' ? `// File: ${kind} tokens for Jetpack Compose.\n` : `// File: ${kind} tokens for SwiftUI.\n`);
